const KEY="nutrition-v1";
const today=()=>new Date().toISOString().slice(0,10);
const defaults={started:today(),freeUsed:{},meals:{},weights:{},workouts:{},loadings:{}};
let s=JSON.parse(localStorage.getItem(KEY)||"null")||defaults;
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
function days(){return Math.max(1,Math.floor((new Date(today())-new Date(s.started))/86400000)+1)}
function freeEarned(){return days()*150}
function freeUsed(){return Object.values(s.freeUsed).reduce((a,b)=>a+(+b||0),0)}
function balance(){return freeEarned()-freeUsed()}
const mealPlan=[
["צום בוקר","3 שעות מתחילת היום – לפי התפריט."],
["ארוחה 1","בחר/י בדיוק את אפשרויות החלבון והפחמימה המוגדרות בתפריט המקורי."],
["ארוחת ביניים","אופציונלית בלבד, בהתאם לתפריט."],
["ארוחה 2","בחר/י בדיוק את אפשרויות החלבון והפחמימה המוגדרות בתפריט המקורי."]
];
let page="today";
function nav(){return '<div class="nav"><button data-p="today">היום</button><button data-p="free">150 חופשי</button><button data-p="loading">העמסה</button><button data-p="progress">מעקב</button></div>'}
function shell(content){app.innerHTML='<div class="wrap"><div class="hero"><h1>התזונה שלי</h1><div class="muted">מעקב יומי לפי התפריט שלך</div></div>'+content+nav()+'</div>';document.querySelectorAll("[data-p]").forEach(b=>{if(b.dataset.p===page)b.classList.add("active");b.onclick=()=>{page=b.dataset.p;render()}})}
function todayPage(){let d=today(),m=s.meals[d]||{};return '<div class="grid"><div class="card"><div class="muted">יתרת 150</div><div class="stat '+(balance()<0?"warn":"good")+'">'+balance()+'</div><div>קלוריות</div></div><div class="card"><div class="muted">משקל היום</div><div class="stat">'+(s.weights[d]||"—")+'</div><div>ק״ג</div></div></div><div class="card"><h2>היום</h2>'+mealPlan.map((x,i)=>'<div class="meal row"><input class="check" type="checkbox" data-meal="'+i+'" '+(m[i]?"checked":"")+'> <div><b>'+x[0]+'</b><div class="muted">'+x[1]+'</div></div></div>').join("")+'</div><div class="card"><h2>אימון כוח</h2><div class="row"><button id="strength" class="'+(s.workouts[d]?"primary":"soft")+'">'+(s.workouts[d]?"✓ בוצע אימון כוח":"סמן אימון כוח")+'</button></div><p class="muted">העמסה שבועית אפשרית רק אחרי אימון כוח ובמקום ארוחת הערב.</p></div>'}
function freePage(){let d=today(),used=+(s.freeUsed[d]||0);return '<div class="card"><h2>בנק 150 קלוריות</h2><div class="stat '+(balance()<0?"warn":"good")+'">'+balance()+'</div><p>כל יום מתווספות 150 קלוריות. מה שלא נוצל נשמר ונצבר לימים הבאים.</p><div class="bar"><div class="fill" style="width:'+Math.min(100,freeUsed()/Math.max(1,freeEarned())*100)+'%"></div></div><p class="muted">נצברו: '+freeEarned()+' · נוצלו: '+freeUsed()+'</p><div class="row"><input id="freeInput" class="amount" type="number" min="0" value="'+used+'"><button id="saveFree" class="primary">שמור שימוש היום</button></div></div>'}
function loadingPage(){let d=today(),can=!!s.workouts[d],done=!!s.loadings[d];return '<div class="card"><h2>העמסה שבועית</h2><p><b>כלל:</b> פעם אחת בשבוע בלבד, רק לאחר אימון כוח, ובמקום ארוחת הערב.</p>'+(can?'<div class="good">✓ אימון כוח מסומן היום</div>':'<div class="warn">עדיין לא סומן אימון כוח היום.</div>')+'<hr><h3>אפשרות 1 — מתוך התפריט</h3><p>חלבון אחד + פחמימה מיוחדת אחת, בדיוק לפי הרשימה בתפריט המקורי.</p><h3>אפשרות 2 — בחוץ</h3><p>5 משולשי פיצה <b>או</b> 5 יחידות סושי <b>או</b> Double McRoyal + שתי מנות צ׳יפס גדולות.</p><p class="muted">האפשרויות חלופיות ולא מצטברות.</p><button id="loadingBtn" '+(!can?"disabled":"")+' class="'+(done?"danger":"primary")+'">'+(done?"בטל העמסה של היום":"סמן העמסה היום")+'</button></div>'}
function progressPage(){let d=today();return '<div class="card"><h2>מעקב משקל</h2><div class="row"><input id="weight" class="amount" type="number" step=".1" value="'+(s.weights[d]||"")+'" placeholder="90.0"><button id="saveWeight" class="primary">שמור</button></div></div><div class="card"><h2>7 ימים אחרונים</h2>'+Array.from({length:7},(_,i)=>{let x=new Date();x.setDate(x.getDate()-i);let k=x.toISOString().slice(0,10);return '<div class="meal"><b>'+k+'</b> — '+(s.weights[k]?s.weights[k]+' ק״ג':'לא הוזן')+'</div>'}).join("")+'</div>'}
function render(){shell(page==="today"?todayPage():page==="free"?freePage():page==="loading"?loadingPage():progressPage());let d=today();document.querySelectorAll("[data-meal]").forEach(c=>c.onchange=()=>{s.meals[d]=s.meals[d]||{};s.meals[d][c.dataset.meal]=c.checked;save()});let el=document.querySelector("#strength");if(el)el.onclick=()=>{s.workouts[d]=!s.workouts[d];save();render()};el=document.querySelector("#saveFree");if(el)el.onclick=()=>{s.freeUsed[d]=Math.max(0,+document.querySelector("#freeInput").value||0);save();render()};el=document.querySelector("#saveWeight");if(el)el.onclick=()=>{s.weights[d]=document.querySelector("#weight").value;save();render()};el=document.querySelector("#loadingBtn");if(el)el.onclick=()=>{if(!s.workouts[d])return;let wk=new Date();wk.setDate(wk.getDate()-7);let recent=Object.keys(s.loadings).some(k=>s.loadings[k]&&new Date(k)>wk&&k!==d);if(!s.loadings[d]&&recent){alert("כבר סומנה העמסה בשבעת הימים האחרונים.");return}s.loadings[d]=!s.loadings[d];save();render()}}
render();